version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: website_session_id
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: primary_product_id
        tests:
          - not_null
      - name: items_purchased
        tests:
          - not_null
      - name: price_usd
        tests:
          - not_null
          - negative_price_test
      - name: cogs_usd
        tests:
          - not_null
          - negative_price_test
  - name: stg_order_items
    columns:
      - name: order_item_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: order_id
        tests: 
          - not_null
      - name: product_id
        tests: 
          - not_null
      - name: is_primary_item
        tests: 
          - not_null
      - name: price_usd
        tests: 
          - not_null
          - negative_price_test
      - name: cogs_usd
        tests: 
          - not_null
          - negative_price_test
  - name: stg_order_item_refunds
    columns:
      - name: order_item_refund_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: order_item_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: refund_amt_usd
        tests:
          - not_null
          - negative_price_test
  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: product_name
        tests:
          - not_null
  - name: stg_website_pageviews
    columns:
      - name: website_pageview_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: website_session_id
        tests:
          - not_null
      - name: pageview_url
        tests:
          - not_null
  - name: stg_website_sessions
    columns:
      - name: website_session_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: user_id
        tests:
          - not_null
      - name: is_repeat_session
        tests:
          - not_null
      - name: device_type
        tests:
          - not_null
