version: 2

models:
  - name: int_dim_users
    columns:
      - name: user_id
        tests:
          - unique
          - not_null
      - name: first_session_date
        tests:
          - not_null
      - name: acquisition_device
        tests:
          - not_null
      - name: is_buyer
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: is_repeat_buyer
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: total_orders
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
