version: 2

models:
  - name: mart_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: user_id
        tests:
          - not_null
      - name: website_session_id
        tests:
          - not_null
      - name: primary_product_id
        tests:
          - not_null
      - name: items_purchased
        tests:
          - not_null
      - name: price_usd
        tests:
          - not_null
          - negative_price_test
      - name: cogs_usd
        tests:
          - not_null
          - negative_price_test
      - name: gross_margin_usd
        tests:
          - not_null
      - name: gross_margin_pct
        tests:
          - not_null
      - name: refund_amt_usd
      - name: net_revenue_usd
        tests:
          - not_null
      - name: order_year
        tests:
          - not_null
      - name: order_month
        tests:
          - not_null
      - name: order_day_of_week
        tests:
          - not_null
  - name: mart_products
    tests:
      - unique:
          column_name: "product_id || '-' || order_year || '-' || order_month"
    columns:
      - name: product_id
        tests:
          - not_null
      - name: product_name
        tests:
          - not_null 
      - name: order_year
        tests:
          - not_null
      - name: order_month
        tests:
          - not_null
      - name: total_revenue
        tests:
          - not_null
          - negative_price_test
      - name: total_cogs
        tests:
          - not_null
          - negative_price_test
      - name: gross_margin_usd
        tests:
          - not_null
      - name: gross_margin_pct
        tests:
          - not_null
      - name: units_sold
      - name: total_refund_amt
      - name: refund_count
      - name: refund_rate_pct
      - name: net_revenue
  - name: mart_sessions
    columns:
      - name: session_id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
          - future_date_test
      - name: user_id
        tests:
          - not_null
      - name: is_repeat_session
        tests:
          - not_null
          - accepted_values:
                values: [0, 1]
      - name: acquisition_channel
      - name: acquisition_campaign
      - name: device_type
          - not_null
      - name: order_id
      - name: price_usd
      - name: is_conversion
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: session_year
        tests:
          - not_null
      - name: session_month
          - not_null
